CREATE DATABASE BASE_DADOS;

USE BASE_DADOS;

CREATE TABLE PESSOA(
    CODIGO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    IDADE INT NOT NULL,
    EMAIL VARCHAR(50) NOT NULL);
    
SELECT * FROM PESSOA;